# Generated by Django 6.0.2 on 2026-03-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimonitor',
            old_name='expexted_status',
            new_name='expected_status',
        ),
        migrations.RemoveField(
            model_name='apimonitor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apimonitor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='status',
            field=models.CharField(default='UP', max_length=10),
        ),
        migrations.AlterField(
            model_name='apimonitor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
