# Generated by Django 6.0.2 on 2026-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_expexted_status_apimonitor_expected_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
