# Generated by Django 6.0.2 on 2026-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_apimonitor_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
