# Generated by Django 6.0.2 on 2026-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_apimonitor_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
