# Generated by Django 6.0.2 on 2026-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_apimonitor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='downtime_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='last_downtime_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
