# Generated by Django 6.0.2 on 2026-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
