# Generated by Django 6.0.2 on 2026-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_apimonitor_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='check_interval',
            field=models.IntegerField(choices=[(30, 'Every 30 seconds'), (60, 'Every 1 minute'), (300, 'Every 5 minutes'), (600, 'Every 10 minutes')], default=60),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='uptime_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
