# Generated by Django 6.0.2 on 2026-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_apimonitor_check_interval_apimonitor_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='response_time_threshold_ms',
            field=models.FloatField(default=1000, help_text='Response time threshold in milliseconds'),
        ),
    ]
