# Generated by Django 6.0.2 on 2026-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_apimonitor_response_time_threshold_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer API Key'), ('x_api_key', 'X-API-Key')], default='none', max_length=20),
        ),
    ]
