# Generated by Django 6.0.2 on 2026-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_apimonitor_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
