# Generated by Django 6.0.2 on 2026-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_apimonitor_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimonitor',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10),
        ),
    ]
