# Generated by Django 6.0.2 on 2026-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_apimonitor_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='expected_response',
            field=models.TextField(blank=True, default='', help_text="Expected response value. For 'contains', enter text that must appear in the response. For 'json', enter valid JSON."),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='response_validation_type',
            field=models.CharField(choices=[('none', 'No Response Validation'), ('contains', 'Response Contains Text'), ('json', 'JSON Response Validation')], default='none', help_text='How the API response should be validated.', max_length=20),
        ),
    ]
