# Generated by Django 6.0.2 on 2026-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_apimonitor_expected_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimonitor',
            name='status',
            field=models.CharField(choices=[('UP', 'UP'), ('SLOW', 'SLOW'), ('DOWN', 'DOWN')], default='UP', max_length=10),
        ),
    ]
