# Generated by Django 6.0.2 on 2026-08-31 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_alter_apimonitor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('down_alert_enabled', models.BooleanField(default=True)),
                ('slow_alert_enabled', models.BooleanField(default=True)),
                ('recovery_alert_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('phone_enabled', models.BooleanField(default=False)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='monitoring.apimonitor')),
            ],
        ),
    ]
