# Generated by Django 6.0.2 on 2026-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APILogs',
            new_name='APILog',
        ),
    ]
