# Generated by Django 6.0.2 on 2026-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_apilogs_apilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='status',
            field=models.CharField(choices=[('UP', 'UP'), ('SLOW', 'SLOW'), ('DOWN', 'DOWN')], max_length=10),
        ),
    ]
